version: "3.8"

x-mq: &mq
  image: rabbitmq:3-management
  environment:
    RABBITMQ_ERLANG_COOKIE: secret
  volumes:
    - ./mq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf

x-app-base: &app-base
  environment:
    SPRING_RABBITMQ_ADDRESSES: "mq1:5672,mq2:5672"
    SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  depends_on: [mq1, mq2]

services:

  mq1:
    <<: *mq
    hostname: usaq1

  mq2:
    <<: *mq
    hostname: usaq2

  sink-service1: &sink-service
    image: sink-service:0.0.1-SNAPSHOT
    <<: *app-base

  sink-service2:
    <<: *sink-service

  source-service1: &source-service
    image: source-service:0.0.1-SNAPSHOT
    <<: *app-base

  source-service2:
    <<: *source-service

  lb:
    image: nginx
    ports: ["8080:8080", "15672:15672"]
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [source-service1, source-service2]

  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]
