version: "3.8"

x-mq: &mq
  image: rabbitmq:3-management
  environment:
    RABBITMQ_ERLANG_COOKIE: secret
  volumes:
    - ./mq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf

x-app-base: &app-base
  environment:
    SPRING_RABBITMQ_ADDRESSES: "mq1:5672,mq2:5672"
  depends_on: [mq1, mq2]

services:

  mq1:
    <<: *mq
    hostname: usaq1
    ports: ["15672:15672"]

  mq2:
    <<: *mq
    hostname: usaq2

  sink-app1: &sink-app
    image: sink-app:0.0.1-SNAPSHOT
    <<: *app-base

  sink-app2:
    <<: *sink-app

  source-app1: &source-app
    image: source-app:0.0.1-SNAPSHOT
    <<: *app-base

  source-app2:
    <<: *source-app

  lb:
    image: nginx
    ports: ["8080:80"]
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [source-app1, source-app2]

