version: "3.8"

x-mq: &mq
  image: rabbitmq:3-management
  environment:
    RABBITMQ_ERLANG_COOKIE: secret
  volumes:
    - ./docker/mq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
  profiles:
    - mq

x-app-base: &app-base
  environment:
    SPRING_RABBITMQ_ADDRESSES: "mq1:5672,mq2:5672,mq3:5672"
    SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
    LOGGING_LEVEL_COM_RABBITMQ_CLIENT_IMPL_RECOVERY_AUTORECOVERINGCONNECTION: DEBUG
  depends_on: [mq1, mq2, mq3]
  profiles:
    - app

services:

  mq1:
    <<: *mq
    hostname: usaq1
    ports: ["15672:15672"]

  mq2:
    <<: *mq
    hostname: usaq2

  mq3:
    <<: *mq
    hostname: usaq3

  consumer-service1: &consumer-service
    image: consumer-service:0.0.1-SNAPSHOT
    command: --spring.cloud.stream.rabbit.bindings.tweet-in-0.consumer.quorum.enabled=true
    <<: *app-base

  consumer-service2:
    <<: *consumer-service

  supplier-service1: &supplier-service
    image: supplier-service:0.0.1-SNAPSHOT
    <<: *app-base

  supplier-service2:
    <<: *supplier-service

  lb:
    image: nginx
    ports: ["8080:8080"]
    volumes:
      - ./docker/lb/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [supplier-service1, supplier-service2]
    profiles:
      - app

  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]
    profiles:
      - app

  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on: [supplier-service1, supplier-service2, consumer-service1, consumer-service2]
    profiles:
      - app

