[tools]
java = "liberica-21"
k6 = "latest"

[tasks.build]
run = [
    "mvn -f services/supplier-service -DskipTests spring-boot:build-image",
    "mvn -f services/consumer-service -DskipTests spring-boot:build-image",
]

[tasks.up]
run = [
    "docker compose --profile mq up -d",
    "sleep 10",
    "docker compose --profile app --profile mq up -d",
]

[tasks.down]
run = [
    "docker compose --profile app --profile mq down",
]

[tasks.logs]
run = "docker compose --profile app --profile mq logs -f --since 0s supplier-service1 supplier-service2 consumer-service1 consumer-service2"

[tasks.requests]
run = "k6 run -d 1h --min-iteration-duration 1s script.js"
